$('a[download]').css('border', '1px solid red'); //Простой атрибут
$('a[href="https://ya.ru"]').css('border', '1px solid red'); //Полное соответствие
$('a[href!="https://ya.ru"]').css('border', '1px solid red'); //Полное несоответствие
$('a[href^="https"]').css('border', '1px solid red'); //Начинается с ....
$('a[href$=".com"]').css('border', '1px solid red'); //Заканчивается на ...
$('a[href*="google"]').css('border', '1px solid red'); //Содержит ...
$('a[href|="main"]').css('border', '1px solid red'); //Иммет префикс - ...
$('a[href][download]').css('border', '1px solid red'); //Имеет одновременно несколько атрибутов
